processors-toolbox:
    processors:
        - type: morpho:PyStanSamplingProcessor
          name: generator
        - type: IOROOTProcessor
          name: writer
        - type: IOJSONProcessor
          name: writer_json
    connections:
        - signal: "generator:data"
          slot: "writer:data"
          order: 2
        - signal: "generator:data"
          slot: "writer_json:data"
          order: 1
generator:
    model_code: "models/model_linear_generator.stan"
    input_data: 
        slope: 1
        intercept: -2
        xmin: 1
        xmax: 10
        sigma: 1.6
    iter: 530
    warmup: 500
    interestParams: ['x','y','residual']
writer:
    action: write
    filename: data/data.root
    variables: ["x","y",'residual']
    tree_name: myTree
writer_json:
    action: write
    filename: data/data.json
    variables: ["x","y",'residual']