processors-toolbox:
    processors:
        - type: morpho:PyStanSamplingProcessor
          name: generator
        - type: IOYAMLProcessor
          name: writer_yaml
        - type: IOROOTProcessor
          name: writer
    connections:
        - signal: "generator:results"
          slot: "writer:data"
        - signal: "generator:results"
          slot: "writer_yaml:data"
generator:
    model_code: "models/model_linear_generator.stan"
    input_data: 
        slope: 1
        intercept: -2
        xmin: 1
        xmax: 10
        sigma: 1.6
    iter: 530
    warmup: 500
    interestParams: ['x','y','residual']
writer:
    action: write
    filename: data/data.root
    variables: 
        - "x"
        - "y"
        - 'residual'
    tree_name: myTree
writer_yaml:
    action: write
    filename: data/data.yaml
    variables: ["x","y",'residual']